import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/header";
import Inner from "./components/inner";
import Mv from "./components/mv";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <Header></Header>
        <Mv></Mv>
        <Inner>
          <div className="my-10">{children}</div>
        </Inner>
      </body>
    </html>
  );
}
